var searchData=
[
  ['cleandata_1391',['cleanData',['../namespaceepidemiology_1_1epidata_1_1cleanData.html',1,'epidemiology::epidata']]],
  ['commuter_5fmigration_5fbfa_1392',['commuter_migration_bfa',['../namespaceepidemiology_1_1epidata_1_1commuter__migration__bfa.html',1,'epidemiology::epidata']]],
  ['de_1393',['de',['../namespaceepi_1_1regions_1_1de.html',1,'epi::regions']]],
  ['defaultdict_1394',['defaultDict',['../namespaceepidemiology_1_1epidata_1_1defaultDict.html',1,'epidemiology::epidata']]],
  ['detail_1395',['detail',['../namespaceepi_1_1detail.html',1,'epi']]],
  ['details_1396',['details',['../namespaceepi_1_1details.html',1,'epi']]],
  ['epi_1397',['epi',['../namespaceepi.html',1,'']]],
  ['epidata_1398',['epidata',['../namespaceepidemiology_1_1epidata.html',1,'epidemiology']]],
  ['epidemiology_1399',['epidemiology',['../namespaceepidemiology.html',1,'']]],
  ['getdataintopandasdataframe_1400',['getDataIntoPandasDataFrame',['../namespaceepidemiology_1_1epidata_1_1getDataIntoPandasDataFrame.html',1,'epidemiology::epidata']]],
  ['getdividata_1401',['getDIVIData',['../namespaceepidemiology_1_1epidata_1_1getDIVIData.html',1,'epidemiology::epidata']]],
  ['getjhdata_1402',['getJHData',['../namespaceepidemiology_1_1epidata_1_1getJHData.html',1,'epidemiology::epidata']]],
  ['getpopulationdata_1403',['getPopulationData',['../namespaceepidemiology_1_1epidata_1_1getPopulationData.html',1,'epidemiology::epidata']]],
  ['getrkidata_1404',['getRKIData',['../namespaceepidemiology_1_1epidata_1_1getRKIData.html',1,'epidemiology::epidata']]],
  ['getrkidatawithestimations_1405',['getRKIDatawithEstimations',['../namespaceepidemiology_1_1epidata_1_1getRKIDatawithEstimations.html',1,'epidemiology::epidata']]],
  ['getsimulationdata_1406',['getSimulationData',['../namespaceepidemiology_1_1epidata_1_1getSimulationData.html',1,'epidemiology::epidata']]],
  ['getvaccinedata_1407',['getVaccineData',['../namespaceepidemiology_1_1epidata_1_1getVaccineData.html',1,'epidemiology::epidata']]],
  ['regions_1408',['regions',['../namespaceepi_1_1regions.html',1,'epi']]]
];
