var searchData=
[
  ['cleandata_1365',['cleanData',['../namespaceepidemiology_1_1epidata_1_1cleanData.html',1,'epidemiology::epidata']]],
  ['commuter_5fmigration_5fbfa_1366',['commuter_migration_bfa',['../namespaceepidemiology_1_1epidata_1_1commuter__migration__bfa.html',1,'epidemiology::epidata']]],
  ['de_1367',['de',['../namespaceepi_1_1regions_1_1de.html',1,'epi::regions']]],
  ['defaultdict_1368',['defaultDict',['../namespaceepidemiology_1_1epidata_1_1defaultDict.html',1,'epidemiology::epidata']]],
  ['detail_1369',['detail',['../namespaceepi_1_1detail.html',1,'epi']]],
  ['details_1370',['details',['../namespaceepi_1_1details.html',1,'epi']]],
  ['epi_1371',['epi',['../namespaceepi.html',1,'']]],
  ['epidata_1372',['epidata',['../namespaceepidemiology_1_1epidata.html',1,'epidemiology']]],
  ['epidemiology_1373',['epidemiology',['../namespaceepidemiology.html',1,'']]],
  ['getdataintopandasdataframe_1374',['getDataIntoPandasDataFrame',['../namespaceepidemiology_1_1epidata_1_1getDataIntoPandasDataFrame.html',1,'epidemiology::epidata']]],
  ['getdividata_1375',['getDIVIData',['../namespaceepidemiology_1_1epidata_1_1getDIVIData.html',1,'epidemiology::epidata']]],
  ['getjhdata_1376',['getJHData',['../namespaceepidemiology_1_1epidata_1_1getJHData.html',1,'epidemiology::epidata']]],
  ['getpopulationdata_1377',['getPopulationData',['../namespaceepidemiology_1_1epidata_1_1getPopulationData.html',1,'epidemiology::epidata']]],
  ['getrkidata_1378',['getRKIData',['../namespaceepidemiology_1_1epidata_1_1getRKIData.html',1,'epidemiology::epidata']]],
  ['getrkidatawithestimations_1379',['getRKIDatawithEstimations',['../namespaceepidemiology_1_1epidata_1_1getRKIDatawithEstimations.html',1,'epidemiology::epidata']]],
  ['getsimulationdata_1380',['getSimulationData',['../namespaceepidemiology_1_1epidata_1_1getSimulationData.html',1,'epidemiology::epidata']]],
  ['getvaccinedata_1381',['getVaccineData',['../namespaceepidemiology_1_1epidata_1_1getVaccineData.html',1,'epidemiology::epidata']]],
  ['regions_1382',['regions',['../namespaceepi_1_1regions.html',1,'epi']]]
];
